### ISSUE TITLE
Feedback system

### ISSUE THREAD

**Issue by henri1i** [he4rt/he4rt-bot-api#2]
## Feature description
Make possible to users send anonymous feedback messages to any other user in the server. Each message will be reviewed by a moderator before being delivered to the final user.

## Use cases
- Users
```message
/feedback <#12345> 
Hey lil jhon123! I was in the call with you before and I really liked the explanation u made about * insert some stuff here *. 
I'm kinda shy and shit, so I don't really want to text you "personally".
```
```message
/feedback <#54321> 
So... I heard u saying some weird shit in the call before. It would be better if u keep that kind of stuff to yourself.
```
- Moderators
    - Each message will be listed in a channel where the moderators will be able to click on approve or decline.
    - If approved, the message will be sent to the user direct message inbox by the bot.
    - If declined, an input will appear to the moderator who triggered it, and a reply will be required. The message will be erased and the reply will be sent back to the user who sent it.

## For whom and why.
For someone who is too embarrassed to send a message directly.

## Requirements
Since the messages will be reviewed, I don't really think requirements are needed.

## Modeling
| Feedbacks |
| -| 
| sender_id | 
| target_id |
| message |

| Feedback Reviews |
| -| 
| feedback_id | 
| staff_id |
| decline_message |
| approved_at |
| declined_at |

**Comment by Novout** [comment]
O BOT já faz o trabalho de receber ticker -> administrar -> enviar, o ideal seria apenas armazenar o feedback. [Mais informações aqui](https://github.com/he4rt/he4rt-bot-next/blob/main/src/commands/judge.ts).

Inclusive não tem como ter a informação do `sender_id` pois o processo é 100% anônimo.
