### ISSUE TITLE
Verificação de URL dos dados do usuário

### ISSUE THREAD

**Issue by Novout** [he4rt/he4rt-bot-api#20]
[#46](https://github.com/he4rt/he4rt-bot-next/issues/46)

**Comment by PedroPMS** [comment]
Resolvido em:

https://github.com/he4rt/he4rt-bot-api/commit/42ee3e61b7010b07da6b3f23fa85ea7f75d336b3
https://github.com/he4rt/he4rt-bot-api/pull/49
