### ISSUE TITLE
Hotfix: Validação de Linkedin e Github

### ISSUE THREAD

**Issue by Novout** [he4rt/he4rt-bot-api#40]
A grande maioria das apresentações não estão criando contas por conta de uma validação feita na API de que obrigatoriamente um usuário precisa passar um link de github e um link de linkedin válido.

Em um grupo que é essencialmente focado em iniciantes, é esperado que a grande maioria dos novos membros (sequer) saibam da existência de github/gitlab/gitbucket, e dizer ao usuário que ele **precisa** criar uma conta para se apresentar é complicado e sensivo. 

Com isso, sugiro a remoção da validação https para uma simples validação de string, como era anteriormente, sendo necessário reverter apenas duas linhas. Uma alternativa seria manter a validação de https, mas ao invés de retornar 422 em caso de falha, a api poderia inserir um valor nulo no lugar.

**Comment by PedroPMS** [comment]
Certo, vou alterar o form request desse endpoint para permitir enviar nulo nesses campos.
