### ISSUE TITLE
Log de entrada e saida

### ISSUE THREAD

**Issue by Luisnadachi** [he4rt/he4rt-bot-api#56]
Como moderador na He4rt, tento todos os dias ficar de olho no canal privado de logs do servidor, mas com foco especificadamente na entrada e saída de membros, com isso pensei numa feature para o bot. 
Em uma sala definida tenha um job do he4rt bot enviando membros que saíram e entraram do servidor, como um adicional de diferença entre os outros bots existentes, enviar uma contagem toda semana do total de membros que saíram e entraram no decorrer do dia.

**Comment by Novout** [comment]
Resolvido na versão `v2.9.0` do client-bot.
