### ISSUE TITLE
[Comando] /apresentar não retorna mensagem

### ISSUE THREAD

**Issue by DanielHe4rt** [he4rt/he4rt-bot-api#62]
Então, tentei usar o /apresentar e agoar estou recebendo um HTTP 500 e não tenho acesso aos logs e nem ambiente de testes.

Rodei o app na versão: 3.10
Front end app: na versão: 1.11
Estou usando: W11 78931278

**Comment by Canhassi12** [comment]
vish

**Comment by Canhassi12** [comment]
sobrou para o canhas

**Comment by cherryramatisdev** [comment]
ai eh foda

**Comment by Herbert-RD** [comment]
eu acho que a gente deveria

**Comment by cherryramatisdev** [comment]
> eu acho que a gente deveria

Concordo
